---

- name: Setup the Git repo
  git:
    name: "{{ item.url }}"
    dest: "/home/vagrant/{{ item.dest }}"
    version: master
    update: no
  with_items:
    - { url : 'https://github.com/dev-sec/ansible-os-hardening.git', dest: 'ansible-os-hardening' }
    - { url : 'https://github.com/teacheraio/ascdso-studio.git', dest: 'ascdso-studio' }
    - { url : 'https://github.com/dev-sec/linux-baseline.git', dest: 'linux-baseline' }
    - { url : 'https://github.com/dev-sec/cis-docker-benchmark.git', dest: 'cis-docker-benchmark' }
  become: yes
  become_user: vagrant
