sudo: required

language: python

cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

env:
  - test=devsecops
  - test=jenkins
  - test=gitlab
  - test=gitlab-runner
  - test=elk
  - test=prod

services:
  - docker

before_install:
  - sudo cat /proc/cpuinfo
  - sudo cat /proc/meminfo
  - sudo free -m
  - sudo apt-get -q update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get install -q -y docker-ce
  - ssh-keygen -f id_rsa -t rsa -b 4096 -C "your_email@example.com" -N ''

install:
  - pip install docker molecule==2.19 # Molecule Installs Ansible

script:
  - cd provisioning && molecule $DEBUG test -s $test

matrix:
  allow_failures:
    - env: test=gitlab # Docker has some issue with gitlab reconfigure, works fine in VM
