---
- src: geerlingguy.pip
- src: geerlingguy.ruby
- src: geerlingguy.docker
- src: geerlingguy.packer
- src: geerlingguy.java
- src: geerlingguy.nginx
- src: geerlingguy.elasticsearch
- src: geerlingguy.kibana
- src: geerlingguy.logstash
- src: rvm.ruby
- src: secfigo.terraform
- src: secfigo.gauntlt
