---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: False
  options:
    config-file: resources/.yamllint
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu1604}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    hostname: "jenkins.local"
provisioner:
  name: ansible
  playbooks:
    create: create.yml
    destroy: destroy.yml
  env:
    ANSIBLE_ROLES_PATH: ../../roles/
  lint:
    name: ansible-lint
    enabled: True
    options:
      exclude:
        - roles/rvm_io.ruby/tasks/rvm.yml
        - roles/geerlingguy.jenkins/tasks/main.yml
        - roles/geerlingguy.jenkins/tasks/settings.yml
scenario:
  name: jenkins
verifier:
  name: testinfra
  lint:
    name: flake8
