---

- name: Install ELK stack
  hosts: all
  become: yes
  become_user: root
  remote_user: root
  vars:
    - elasticsearch_network_host: localhost

  roles:
    - common
    - geerlingguy.nginx
    - geerlingguy.elasticsearch
    - geerlingguy.kibana
    - geerlingguy.logstash
