---

- name: Install base packages
  apt:
    name:
      - build-essential
      - git
      - python-pip
      - python-virtualenv
    update_cache: yes
    state: present

- name: Upgrade pip
  pip:
    name=pip
    version={{ version }}
    state=present
