---

- name: Install Vulnerability Management
  gather_facts: False
  hosts: all
  become: yes

  pre_tasks:
  - name: install python 3
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python2-minimal)
  - name: Run setup again for gather facts
    setup:
  - name: Fix hash mismatch error
    apt:
       update_cache: yes

  vars:
    # host entries won't work in docker
    # see https://stackoverflow.com/questions/28327458/how-to-add-my-containers-hostname-to-etc-hosts
    # TODO implement dojo role
    add_host_entries: true

  roles:
    - common
    - dojo
