---

- name: Install Jenkins
  gather_facts: False
  hosts: all
  become: yes

  pre_tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal)
  - name: Run setup again for gather facts
    setup:
  - name: Fix hash mismatch error
    apt:
       update_cache: yes

  vars:
    oracle_java_version: 8

    #Gauntlt needs ruby installed
    ruby_version: 'ruby-2.3.1'
    rvm1_rubies: ['{{ ruby_version }}']
    rvm1_user: 'root'
    rvm1_install_path: '/usr/local/rvm'

    # host entries won't work in docker
    # see https://stackoverflow.com/questions/28327458/how-to-add-my-containers-hostname-to-etc-hostl
    add_host_entries: true

    #Jenkins
    jenkins_admin_username: vagrant
    jenkins_admin_password: vagrant
    jenkins_plugins_install_dependencies: yes
    jenkins_java_options: "-Djenkins.install.runSetupWizard=false"
    jenkins_plugins:
      - git # Installs Credentials and SSH credentials plugins
      - sonar
      - ant
      - gradle
      - cloudbees-folder
      - ssh
      - ws-cleanup
      - build-timeout
      - timestamper
      - credentials-binding
      - role-strategy
      - antisamy-markup-formatter
      - ansicolor
      - matrix-auth
      - workflow-aggregator
      - extended-read-permission
      - ssh-slaves
      - email-ext
      - ansible
      - gitlab-plugin

  roles:
    - common # need curl for rvm_io.ruby
    - rvm_io.ruby
    - secfigo.gauntlt
    - geerlingguy.docker
    - geerlingguy.java
    - geerlingguy.jenkins
    - jenkins # Docker settings for jenkins
    - python
    - cli-tools
    - geerlingguy.ansible-role-packer
    # - selenium
