---

- name: Install Security Tools
  apt:
    name:
      - nikto
      - nmap
      - sqlmap
    state: present

- name: Install tools via pip
  pip:
    name:
      - sslyze
      - ansible
      - ansible-lint
    state: present
