---

- name: Install Security Tools
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - nikto
    - nmap
    - sqlmap

- name: Install tools via pip
  pip:
    name:
      - sslyze
      - ansible
    state: present
